51bootcamp/HappyBugs

Frontend/app/src/main/AndroidManifest.xml, Frontend/app/src/main/java/io/happybugs/happybugs/SignInActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/SignUpActivity.java, Frontend/app/src/main/res/layout/activity_sign_in.xml, Frontend/app/src/main/res/layout/activity_sign_up.xml, Frontend/app/src/main/res/values/strings.xml
Due to SignUp activity's dependency on SignIn activity, commited two things at once just this time.
#35 #36
- Changed manifest to arrange SignInActivity firstly
- Created SignIn&Up UI
=> Issue #35 #36, Create SignIn/Up UI

Backend/router/v1/report.ctrl.js, Backend/router/v1/report.js
=> make report  API for create, delete, read, list part

Backend/router/v1/user.js
#17 Check whether the account is already signed up
#18 Create database table, Inserting user information into the database
#19 Catch the error
=> Issue #17 #18 #19 signup

Backend/router/v1/user.js
=> Signup issue17 18 19

Backend/router/v1/report.ctrl.js, Backend/router/v1/report.js
=> make report API for edit part

Frontend/.idea/misc.xml, Frontend/app/src/main/AndroidManifest.xml, Frontend/app/src/main/java/io/happybugs/happybugs/ReportActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/ReportButtons.java, Frontend/app/src/main/java/io/happybugs/happybugs/ReportCheckBoxes.java, Frontend/app/src/main/java/io/happybugs/happybugs/ReportEditTexts.java, Frontend/app/src/main/java/io/happybugs/happybugs/ReportViews.java, Frontend/app/src/main/res/layout/activity_report.xml, Frontend/app/src/main/res/values/strings.xml
=> Issue#20: Add report view

Backend/router/v1/user.js
The password length should be between 6 and 16.
Send an error message if different the scope.
=> issue #51 : Check valid password length

Frontend/app/src/main/java/io/happybugs/happybugs/activity/SignInActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/SignUpActivity.java, Frontend/app/src/main/res/layout/activity_sign_in.xml, Frontend/app/src/main/res/layout/activity_sign_up.xml
=> Issue #66: Equalize sign up view-id with activity variable name

Frontend/.gitignore, Frontend/app/src/main/java/io/happybugs/happybugs/activity/SignUpActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/network/RetrofitInstance.java, Frontend/app/src/main/res/layout/activity_sign_up.xml
=> Issue #62: Connect SignUp view with server

Frontend/app/src/main/java/io/happybugs/.idea/modules.xml, Frontend/app/src/main/java/io/happybugs/.idea/workspace.xml, Frontend/app/src/main/java/io/happybugs/happybugs/APIInterface/APIInterface.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportEditTexts.java
This deals the same issue dealt on Issue #54.
Please ignore issue #54 and comment anything that need to be pointed out here.
Any branch or issue that was worked for #54 will be deleted after the current gets merged.
=> Issue#69-Connect report view to server

Frontend/app/build.gradle, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportEditTexts.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportViews.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/whoTextChange.java, Frontend/app/src/main/res/layout/activity_report.xml, Frontend/app/src/main/res/values/colors.xml
Add facebook profile for the perpetrator.
Needs further factoring and debugging.
=> Issue#56-Add facebook profile UI on report view

Frontend/app/src/main/java/io/happybugs/happybugs/activity/MainActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewAdapter.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewItem.java, Frontend/app/src/main/res/layout/content_main.xml, Frontend/app/src/main/res/layout/report_listview_item.xml, Frontend/app/src/main/res/values/strings.xml, Frontend/app/src/main/res/values/styles.xml
=> Issue #49 show report list at home view

Frontend/app/src/main/java/io/happybugs/happybugs/activity/MainActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java
=> Issue #83: link Reportactivity and MainActivity

Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/WhoTextChange.java, Frontend/app/src/main/res/layout/activity_report.xml
Debugged enabling who checkbox and facebook profile url getting erased.
=> Issue#76 debug facebook profile view

Frontend/app/src/main/java/io/happybugs/happybugs/activity/SignInActivity.java
#72 
Need more improvements:
Handling response specifically depending on ResponseBody
=> Issue #72: response management in SignIn

Frontend/app/src/main/res/layout/content_main.xml, Frontend/app/src/main/res/layout/report_listview_item.xml, Frontend/app/src/main/res/values/strings.xml
=> Issue #95 Modify report list view as UX mocks

Frontend/app/src/main/java/io/happybugs/happybugs/activity/MainActivity.java, Frontend/app/src/main/res/menu/bottom_navigation_main.xml
=> Issue #97 add bottom navigation function

Backend/router/v1/report.ctrl.js, Backend/router/v1/report.js
#55 
To send the error code will be resolved by another issue (#60) .
=> Issue #55 Improve report part

Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportButtons.java, Frontend/app/src/main/res/layout/activity_report.xml
Added delete report button on report view.
Report gets deleted and view connects to home.
=> Issue#110-Add delete report activity

Frontend/app/src/main/AndroidManifest.xml, Frontend/app/src/main/java/io/happybugs/happybugs/activity/KeyboardActionResult.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java
Added keyboard in report view.
Keyboard automatically opens on question click.
=> Iss#87 add keyboard

Frontend/app/src/main/java/io/happybugs/happybugs/activity/CloseReportDialog.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java, Frontend/app/src/main/res/values/strings.xml
Dialog pops up for closing report.
Added confirmation for erasing report.
=> Issue#123-add-dialog-onCloseReport

Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportEditTexts.java
Added perpetrator's facebook ID url data for POST.
=> Issue#130-add-perpetrator-facebookID-POST

Frontend/app/src/main/java/io/happybugs/happybugs/activity/SignUpActivity.java
=> Issue #138 Fix SignUp Bugs

Frontend/app/src/main/AndroidManifest.xml, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java
Considering user's experience, what text is opened when first landing on create report page.
=> Issue#134-add-whatText-toOpen

Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java
=> Issue #133 fix creating report

Backend/router/v1/report.ctrl.js
=> Issue#121-103-find-report

Frontend/app/src/main/java/io/happybugs/happybugs/APIInterface/APIInterface.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewAdapter.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewItem.java
=> [WIP] Issue #144 Delete report

Backend/router/v1/report.ctrl.js
=> Issue#101 add perpetrators part in update report part

Frontend/app/src/main/java/io/happybugs/happybugs/APIInterface/APIInterface.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/MainActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewAdapter.java, Frontend/app/src/main/res/layout/report_listview_item.xml, Frontend/app/src/main/res/values/strings.xml
=> Issue#147 edit report, bug fixed

Backend/models/perpetrator.js, Backend/router/v1/report.ctrl.js
=> Check when perpetrator is null in Create report part

Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewAdapter.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/SignInActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/SignUpActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/SplashScreen.java, Frontend/app/src/main/res/layout/report_listview_item.xml, Frontend/app/src/main/res/values/strings.xml
=> Issue#166-modify-delay-millies

Frontend/app/src/main/java/io/happybugs/happybugs/activity/CloseReportDialog.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewAdapter.java, Frontend/app/src/main/res/layout/report_listview_item.xml
=> Issue#170 fix bugs in reportactivity

Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewAdapter.java
=> Issue#175 XML mismatch hotfix

Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewAdapter.java, Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewItem.java
=> Issue#182-hotfix

Frontend/app/src/main/java/io/happybugs/happybugs/activity/MainActivity.java, Frontend/app/src/main/res/layout/activity_intro.xml, Frontend/app/src/main/res/layout/intro_slide_2.xml, Frontend/app/src/main/res/layout/intro_slide_3.xml
=> Issue#186-modify-intro

Backend/router/v1/report.ctrl.js
=> Issue#187: Fix null perpetrator_id

TestCode/create_report_test.py
Test code for create report.
Needs more features to ensure atomicity of creating report.
#159
=> [WIP] Issue #159 test create report

Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewAdapter.java
=> Issue #181 show intropage. zero state

Frontend/app/src/main/java/io/happybugs/happybugs/activity/SignInActivity.java
=> Issue#190-add-login-attempt-msg
